apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-product-service
  namespace: dev
spec:
  selector:
    matchLabels:
      app: mysql-product-service
      namespace: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-product-service
        namespace: dev
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-cm
                  key: product-db
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-product-pvc