apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: product-service
type: kubernetes.io/basic-auth
stringData:
  password: root
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: auth-service
type: kubernetes.io/basic-auth
stringData:
  password: root