apiVersion: v1
kind: Service
metadata:
  name: mysql-product-service
  namespace: dev
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-product-service