apiVersion: v1
kind: Service
metadata:
  name: mysql-product-service
  namespace: product-service
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-product-service
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-auth-service
  namespace: auth-service
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-auth-service