
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url:  jdbc:mysql://mysql-product-service.dev.svc.cluster.local:3306/platform-order
    url: jdbc:mysql://localhost:3306/platform-order
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    streams:
      application-id: "order-stream"
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: "*"
      state-dir: C:\software\kafka_2.13-3.6.1\kafka-streams
