apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dev
spec:
  ports:
    - name: backend-service
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend-service
    namespace: dev
  type: LoadBalancer