apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-product-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-product-service
      namespace: dev
  template:
    metadata:
      labels:
        app: app-product-service
        namespace: dev
    spec:
      containers:
        - name: product-service
          image: product-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081