apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: dev
spec:
  ports:
    - name: product-service
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: app-product-service
    namespace: dev